# World Explorer content (original facts, clues and passages).
# (iso numeric id in world-atlas, display name, ISO2, capital, level "A"/"B", kid fact)
COUNTRIES = [
("840","United States","us","Washington, D.C.","A","It has 50 states, from snowy Alaska to sunny Hawaii."),
("124","Canada","ca","Ottawa","A","It is the second-biggest country in the world, with more lakes than any other."),
("484","Mexico","mx","Mexico City","A","Chocolate and corn were first grown here long ago."),
("076","Brazil","br","Brasília","A","Most of the Amazon rainforest is here."),
("032","Argentina","ar","Buenos Aires","A","It stretches from hot jungles down to icy Patagonia."),
("604","Peru","pe","Lima","A","The ancient mountain city of Machu Picchu is here."),
("826","United Kingdom","gb","London","A","Big Ben's bell rings in its capital."),
("250","France","fr","Paris","A","The Eiffel Tower stands in its capital."),
("643","Russia","ru","Moscow","A","It is the biggest country in the world and spans 11 time zones."),
("156","China","cn","Beijing","A","The Great Wall and giant pandas are here."),
("356","India","in","New Delhi","A","The Taj Mahal is here, and more people live here than anywhere else."),
("392","Japan","jp","Tokyo","A","It is a chain of islands with Mount Fuji, a tall volcano."),
("036","Australia","au","Canberra","A","Kangaroos and koalas live here, and it is a country AND a continent."),
("818","Egypt","eg","Cairo","A","The great pyramids stand near the Nile River."),
("710","South Africa","za","Pretoria","A","Penguins live on its beaches, and it has three capital cities. Pretoria is one of them."),
("152","Chile","cl","Santiago","B","It is long and skinny, squeezed between the Andes and the Pacific."),
("170","Colombia","co","Bogotá","B","It grows lots of coffee and has coasts on two oceans."),
("862","Venezuela","ve","Caracas","B","Angel Falls, the tallest waterfall in the world, is here."),
("218","Ecuador","ec","Quito","B","It is named after the equator, and it owns the Galápagos Islands."),
("068","Bolivia","bo","Sucre","B","It has a giant salt flat that looks like a mirror after rain."),
("600","Paraguay","py","Asunción","B","It is one of only two landlocked countries in South America."),
("858","Uruguay","uy","Montevideo","B","It won the very first soccer World Cup in 1930."),
("192","Cuba","cu","Havana","B","It is the biggest island in the Caribbean."),
("320","Guatemala","gt","Guatemala City","B","Ancient Maya pyramids rise out of its jungles."),
("188","Costa Rica","cr","San José","B","It has no army and is famous for sloths and volcanoes."),
("591","Panama","pa","Panama City","B","A famous canal here lets ships cross between two oceans."),
("724","Spain","es","Madrid","B","Spanish started here, and flamenco dancing too."),
("620","Portugal","pt","Lisbon","B","Explorers sailed from here long ago to find new sea routes."),
("276","Germany","de","Berlin","B","It has thousands of castles and invented the first printing press with movable type in Europe."),
("380","Italy","it","Rome","B","It is shaped like a boot, and pizza comes from here."),
("528","Netherlands","nl","Amsterdam","B","It is famous for windmills, tulips and bikes."),
("056","Belgium","be","Brussels","B","It is famous for waffles and chocolate."),
("756","Switzerland","ch","Bern","B","The Alps cover much of it, and it is famous for cheese with holes."),
("040","Austria","at","Vienna","B","The composer Mozart was born here."),
("616","Poland","pl","Warsaw","B","The scientist Marie Curie was born here."),
("752","Sweden","se","Stockholm","B","It has a hotel made completely of ice."),
("578","Norway","no","Oslo","B","Long sea inlets called fjords cut into its coast."),
("246","Finland","fi","Helsinki","B","It has saunas and around 188,000 lakes."),
("208","Denmark","dk","Copenhagen","B","LEGO bricks were invented here."),
("372","Ireland","ie","Dublin","B","It is called the Emerald Isle because it is so green."),
("300","Greece","gr","Athens","B","The Olympic Games began here long ago."),
("804","Ukraine","ua","Kyiv","B","It is the biggest country that is completely in Europe."),
("792","Turkey","tr","Ankara","B","Its biggest city, Istanbul, sits on two continents."),
("352","Iceland","is","Reykjavík","B","It has volcanoes, glaciers and hot springs."),
("203","Czechia","cz","Prague","B","Its capital has a famous clock from the 1400s that still works."),
("348","Hungary","hu","Budapest","B","The Rubik's Cube was invented here."),
("642","Romania","ro","Bucharest","B","The Carpathian Mountains curve through it."),
("682","Saudi Arabia","sa","Riyadh","B","Much of it is desert, with huge sand dunes."),
("364","Iran","ir","Tehran","B","It is famous for beautiful hand-woven carpets."),
("368","Iraq","iq","Baghdad","B","Some of the world's first cities were built between its two rivers."),
("376","Israel","il","Jerusalem","B","The Dead Sea is so salty that you float easily."),
("586","Pakistan","pk","Islamabad","B","K2, the second-tallest mountain, is on its border."),
("004","Afghanistan","af","Kabul","B","It is a landlocked, mountainous country."),
("398","Kazakhstan","kz","Astana","B","It is the biggest landlocked country in the world."),
("496","Mongolia","mn","Ulaanbaatar","B","Many families live in round tents called gers."),
("410","South Korea","kr","Seoul","B","It is known for K-pop and kimchi."),
("408","North Korea","kp","Pyongyang","B","It shares a peninsula with South Korea."),
("704","Vietnam","vn","Hanoi","B","It is long and shaped like the letter S."),
("764","Thailand","th","Bangkok","B","Elephants are a national symbol here."),
("360","Indonesia","id","Jakarta","B","It is made of more than 17,000 islands."),
("608","Philippines","ph","Manila","B","It is a country of more than 7,000 islands."),
("458","Malaysia","my","Kuala Lumpur","B","Its capital has famous twin towers."),
("524","Nepal","np","Kathmandu","B","Mount Everest, the tallest mountain, is on its border."),
("050","Bangladesh","bd","Dhaka","B","The Bengal tiger is its national animal."),
("554","New Zealand","nz","Wellington","B","It has more sheep than people."),
("598","Papua New Guinea","pg","Port Moresby","B","More than 800 languages are spoken here."),
("566","Nigeria","ng","Abuja","B","More people live here than in any other African country."),
("404","Kenya","ke","Nairobi","B","Lions, zebras and giraffes roam its savanna."),
("231","Ethiopia","et","Addis Ababa","B","Coffee was first discovered here."),
("504","Morocco","ma","Rabat","B","It sits just across the sea from Spain."),
("012","Algeria","dz","Algiers","B","It is the biggest country in Africa."),
("288","Ghana","gh","Accra","B","It is one of the world's top cocoa growers."),
("834","Tanzania","tz","Dodoma","B","Mount Kilimanjaro, Africa's tallest mountain, is here."),
("450","Madagascar","mg","Antananarivo","B","Lemurs live here and nowhere else in the wild."),
("180","DR Congo","cd","Kinshasa","B","The mighty Congo River flows through its rainforest."),
("024","Angola","ao","Luanda","B","It has a long coast on the Atlantic Ocean."),
("729","Sudan","sd","Khartoum","B","It has more ancient pyramids than Egypt."),
("434","Libya","ly","Tripoli","B","Most of it is part of the Sahara Desert."),
]
# Countries with land on two continents: either answer counts.
TWO_CONTINENTS = {"Russia": ["Europe", "Asia"], "Turkey": ["Asia", "Europe"], "Kazakhstan": ["Asia", "Europe"], "Egypt": ["Africa", "Asia"]}
OCEANS = [("Pacific Ocean", [-150, 5]), ("Pacific Ocean", [165, -5]), ("Atlantic Ocean", [-35, 20]), ("Atlantic Ocean", [-15, -25]), ("Indian Ocean", [78, -22]), ("Arctic Ocean", [20, 80]), ("Southern Ocean", [40, -62])]
CONTINENTS = ["Africa", "Antarctica", "Asia", "Europe", "North America", "Oceania", "South America"]
HUNTS = [
dict(level="A", title="Around the World", clues=[
 ("Start in the biggest country in the world.", "Russia"),
 ("Go south-east to the country with the Great Wall and giant pandas.", "China"),
 ("Hop across the sea to the island country with Mount Fuji.", "Japan"),
 ("Fly far south to the country where kangaroos hop.", "Australia"),
 ("Cross the Indian Ocean to the country with the pyramids.", "Egypt"),
]),
dict(level="A", title="The Americas Trip", clues=[
 ("Start in the country with 50 states.", "United States"),
 ("Go north to the second-biggest country in the world.", "Canada"),
 ("Fly south past the USA to the country where chocolate was first grown.", "Mexico"),
 ("Keep going south to the country with most of the Amazon rainforest.", "Brazil"),
 ("Go south-west to the country that stretches down to icy Patagonia.", "Argentina"),
]),
dict(level="B", title="Europe Express", clues=[
 ("Start where Spanish and flamenco began.", "Spain"),
 ("Go north-east over the mountains to the country with the Eiffel Tower.", "France"),
 ("Head east to the country with thousands of castles.", "Germany"),
 ("Go north across the water to where LEGO was invented.", "Denmark"),
 ("Go south all the way to the boot-shaped country.", "Italy"),
]),
dict(level="B", title="Mountains & Rivers", clues=[
 ("Begin in the small mountain country on the border of Mount Everest (not China).", "Nepal"),
 ("Go south to the huge country with the Taj Mahal.", "India"),
 ("Fly west across the Arabian Sea and Arabia to Africa's country where coffee was discovered.", "Ethiopia"),
 ("Go south to the country with Mount Kilimanjaro.", "Tanzania"),
 ("Go west to the country with the mighty Congo River.", "DR Congo"),
]),
dict(level="B", title="Island Hopper", clues=[
 ("Start on the biggest island in the Caribbean.", "Cuba"),
 ("Fly across the Atlantic to the island of volcanoes and glaciers in the far north.", "Iceland"),
 ("Fly south-east to the Emerald Isle.", "Ireland"),
 ("Travel far to the island off Africa where lemurs live.", "Madagascar"),
 ("End in the country of more than 17,000 islands.", "Indonesia"),
]),
]
# Original "read, then find it" passages. The place is NOT named; kids read and then tap it.
PASSAGES = [
("China", "Mei lives in a busy city where bicycles and scooters zoom past tall buildings. On weekends her family visits a huge wall that winds over the mountains like a stone dragon. At the zoo, she always waves to the black-and-white bears munching bamboo. Find Mei's country!"),
("Egypt", "Omar rides a camel across golden sand. In the distance, three giant triangles of stone point at the sky. They were built thousands of years ago for kings called pharaohs. A long river flows nearby and turns the desert green. Where is Omar?"),
("Brazil", "Lucas paddles a canoe along a wide brown river. Monkeys chatter in the trees, and bright parrots flash red and blue. This rainforest is the largest in the world. Lucas speaks Portuguese. Find his country!"),
("Australia", "Ruby wakes up to a bird that sounds like it is laughing. Outside, a mother animal hops by with a baby peeking out of her pouch. Ruby's country is so big that it is also a whole continent. Where does Ruby live?"),
("Canada", "Noah ties on his skates and glides across a frozen lake. Maple trees surround the lake, and a red maple leaf is on his country's flag. Moose sometimes wander right into town! Find Noah's country."),
("Japan", "Hana eats breakfast with chopsticks: rice, soup and fish. From her window she can see a tall, snow-capped volcano. Her country is made of many islands, and its trains are super fast. Where is Hana?"),
("India", "Priya's family celebrates a festival of lights with little lamps and fireworks. They visit a white marble palace with a beautiful dome. Elephants and tigers live in her country's forests. Find Priya's country!"),
("Mexico", "Sofía helps her grandma make tortillas from corn. Tonight there is a party with music and a colorful piñata. People here speak Spanish, and long ago they were among the first to grow chocolate. Where is Sofía?"),
("Kenya", "Baraka watches a herd of zebras race across the grassland. A giraffe stretches its neck to nibble a tree, and a lion naps in the shade. His country is in East Africa, right on the equator. Find Baraka's country!"),
("Italy", "Giulia and her brother share a pizza in a sunny square. Their country is shaped like a tall boot kicking a ball. In the capital, they visit a giant old stadium where gladiators once fought. Where are they?"),
]
