# Mandarin content. The first 12 characters (and their hints) come from the Chinese Writing Fun workbook
# (/workspace/chinese-writing-fun-src/make_workbook.py). Everything is checked against pypinyin in build_data.py.
# (hanzi, pinyin, meaning, group, emoji, hint)
CHARS = [
("一","yī","one","Numbers","1️⃣","One line. Start on the left and slide to the right."),
("二","èr","two","Numbers","2️⃣","Two lines. A short one on top, a longer one on the bottom."),
("三","sān","three","Numbers","3️⃣","Three lines. Top, then middle, then a longer line at the bottom."),
("四","sì","four","Numbers","4️⃣","A box with two little legs inside."),
("五","wǔ","five","Numbers","5️⃣","Top line, a down-and-over stroke, then a long base."),
("六","liù","six","Numbers","6️⃣","A dot hat, a line, then two little feet."),
("七","qī","seven","Numbers","7️⃣","A line crossed by a hook that bends right."),
("八","bā","eight","Numbers","8️⃣","Two strokes leaning apart, like a little tent."),
("九","jiǔ","nine","Numbers","9️⃣","A slash, then a big hook that sweeps right."),
("十","shí","ten","Numbers","🔟","A plus sign: across, then down."),
("人","rén","person","People & size","🧍","Like a walking person. Left slash, then right slash."),
("大","dà","big","People & size","🐘","A person with arms stretched wide. Line, left slash, right slash."),
("小","xiǎo","small","People & size","🐭","A hook in the middle with a dot on each side."),
("中","zhōng","middle","People & size","🎯","A box with a line straight through the middle."),
("上","shàng","up / above","People & size","⬆️","A short line pointing up from the ground."),
("下","xià","down / below","People & size","⬇️","A line with a stroke hanging below it."),
("好","hǎo","good","People & size","👍","女 (woman) next to 子 (child) means good."),
("爸","bà","dad","Family","👨","父 (father) on top of 巴."),
("妈","mā","mom","Family","👩","女 (woman) next to 马 (horse). It sounds like mǎ."),
("哥","gē","older brother","Family","👦","Two 可 stacked on top of each other."),
("姐","jiě","older sister","Family","👧","女 (woman) next to 且."),
("弟","dì","younger brother","Family","🧒","Two little horns on top, then a winding shape."),
("妹","mèi","younger sister","Family","👶","女 (woman) next to 未."),
("家","jiā","home / family","Family","🏠","A roof (宀) over a pig (豕). Long ago families kept pigs at home!"),
("口","kǒu","mouth","Body","👄","Draw a square: left side, then top and right, then the bottom."),
("目","mù","eye","Body","👁️","A tall box with two lines inside, like an eye standing up."),
("耳","ěr","ear","Body","👂","A tall shape with lines, like the folds of an ear."),
("手","shǒu","hand","Body","✋","A slash on top, then lines like fingers, then a hook."),
("足","zú","foot","Body","🦶","A mouth (口) on top of a walking foot."),
("头","tóu","head","Body","🙆","Two dots, then a big 大 underneath."),
("心","xīn","heart","Body","❤️","A curved hook with three dots, like a beating heart."),
("日","rì","sun / day","Nature","☀️","A tall window-box with one line across the middle."),
("月","yuè","moon / month","Nature","🌙","A skinny moon-window with two little lines inside."),
("山","shān","mountain","Nature","⛰️","A tall peak in the middle, with a smaller peak on each side."),
("水","shuǐ","water","Nature","💧","A middle line with a hook, then three little splashes."),
("火","huǒ","fire","Nature","🔥","Two sparks on top, then a person-shape underneath."),
("木","mù","tree / wood","Nature","🌳","A plus sign with two branches, like a tree."),
("天","tiān","sky / day","Nature","🌤️","Two lines on top of 人: the sky above a person."),
("雨","yǔ","rain","Nature","🌧️","A cloud box with raindrops inside."),
("花","huā","flower","Nature","🌸","Grass on top (艹) and 化 below."),
("土","tǔ","soil / earth","Nature","🟫","A short line, a tall line, then a long ground line."),
("石","shí","stone","Nature","🪨","A cliff with a stone (口) underneath."),
("吃","chī","to eat","Verbs","🍽️","A mouth (口) next to 乞. You eat with your mouth!"),
("喝","hē","to drink","Verbs","🥤","Another mouth (口) word: drinking."),
("看","kàn","to look","Verbs","👀","A hand (手) over an eye (目): shading your eyes to look."),
("走","zǒu","to walk","Verbs","🚶","土 on top of a walking foot."),
("说","shuō","to speak","Verbs","🗣️","The speech side (讠) next to 兑."),
("来","lái","to come","Verbs","👋","A tree-like shape with two dots."),
("去","qù","to go","Verbs","🏃","土 on top of 厶."),
("坐","zuò","to sit","Verbs","🪑","Two people (人人) sitting on the ground (土)."),
("飞","fēi","to fly","Verbs","🕊️","A sweeping hook with two little wings."),
("爱","ài","to love","Verbs","💕","A hand on top, a cover, and a friend (友) underneath."),
]

# Tone sets: (base syllable, [(hanzi, pinyin, meaning) x4 tones])
TONES = [
("ma", [("妈","mā","mom"),("麻","má","hemp"),("马","mǎ","horse"),("骂","mà","scold")]),
("yi", [("衣","yī","clothes"),("姨","yí","aunt"),("椅","yǐ","chair"),("意","yì","meaning")]),
("ba", [("八","bā","eight"),("拔","bá","pull out"),("把","bǎ","hold"),("爸","bà","dad")]),
("shi",[("诗","shī","poem"),("十","shí","ten"),("使","shǐ","use"),("是","shì","is")]),
("wu", [("屋","wū","house"),("无","wú","none"),("五","wǔ","five"),("雾","wù","fog")]),
("tang",[("汤","tāng","soup"),("糖","táng","candy"),("躺","tǎng","lie down"),("烫","tàng","very hot")]),
("hu", [("呼","hū","breathe out"),("胡","hú","beard"),("虎","hǔ","tiger"),("户","hù","door")]),
("fu", [("夫","fū","man"),("福","fú","luck"),("斧","fǔ","axe"),("父","fù","father")]),
]

# Phrases: (category, hanzi, pinyin, english)
PHRASES = [
("Greetings","你好","nǐ hǎo","hello"),
("Greetings","早上好","zǎoshang hǎo","good morning"),
("Greetings","晚安","wǎn'ān","good night"),
("Greetings","再见","zàijiàn","goodbye"),
("Polite words","谢谢","xièxie","thank you"),
("Polite words","不客气","bú kèqi","you're welcome"),
("Polite words","对不起","duìbuqǐ","sorry"),
("Polite words","没关系","méi guānxi","that's OK"),
("Polite words","请","qǐng","please"),
("About me","我叫小明。","Wǒ jiào Xiǎomíng.","My name is Xiaoming."),
("About me","你叫什么名字？","Nǐ jiào shénme míngzi?","What is your name?"),
("About me","我七岁。","Wǒ qī suì.","I am seven years old."),
("About me","我是美国人。","Wǒ shì Měiguó rén.","I am American."),
("About me","很高兴认识你！","Hěn gāoxìng rènshi nǐ!","Nice to meet you!"),
("Numbers","一二三","yī èr sān","one, two, three"),
("Numbers","十","shí","ten"),
("Numbers","一百","yìbǎi","one hundred"),
("Colors","红色","hóngsè","red"),
("Colors","蓝色","lánsè","blue"),
("Colors","黄色","huángsè","yellow"),
("Colors","绿色","lǜsè","green"),
("Colors","白色","báisè","white"),
("Colors","黑色","hēisè","black"),
("Family","爸爸","bàba","dad"),
("Family","妈妈","māma","mom"),
("Family","哥哥","gēge","older brother"),
("Family","姐姐","jiějie","older sister"),
("Family","弟弟","dìdi","younger brother"),
("Family","妹妹","mèimei","younger sister"),
("Family","爷爷","yéye","grandpa (dad's dad)"),
("Family","奶奶","nǎinai","grandma (dad's mom)"),
("Food","米饭","mǐfàn","rice"),
("Food","面条","miàntiáo","noodles"),
("Food","饺子","jiǎozi","dumplings"),
("Food","苹果","píngguǒ","apple"),
("Food","香蕉","xiāngjiāo","banana"),
("Food","牛奶","niúnǎi","milk"),
("Food","我饿了。","Wǒ è le.","I'm hungry."),
("Food","好吃！","Hǎochī!","Yummy!"),
]

# Listening: (hanzi, pinyin, english, emoji)
LISTEN = [
("猫","māo","cat","🐱"),("狗","gǒu","dog","🐶"),("鱼","yú","fish","🐟"),("鸟","niǎo","bird","🐦"),("熊猫","xióngmāo","panda","🐼"),("马","mǎ","horse","🐴"),
("苹果","píngguǒ","apple","🍎"),("香蕉","xiāngjiāo","banana","🍌"),("米饭","mǐfàn","rice","🍚"),("面条","miàntiáo","noodles","🍜"),("牛奶","niúnǎi","milk","🥛"),("饺子","jiǎozi","dumplings","🥟"),
("太阳","tàiyáng","sun","☀️"),("月亮","yuèliang","moon","🌙"),("花","huā","flower","🌸"),("雨","yǔ","rain","🌧️"),("书","shū","book","📚"),("汽车","qìchē","car","🚗"),
("红色","hóngsè","red","🟥"),("蓝色","lánsè","blue","🟦"),("绿色","lǜsè","green","🟩"),("黄色","huángsè","yellow","🟨"),
]

INITIALS = ["b","p","m","f","d","t","n","l","g","k","h","j","q","x","zh","ch","sh","r","z","c","s"]
