# name: (abbr, capital, region, fun fact used in clues). Regions use the common 5-region school model.
STATES = {
"Alabama":("AL","Montgomery","Southeast","Its city Huntsville is called Rocket City."),
"Alaska":("AK","Juneau","West","It is the biggest state of all."),
"Arizona":("AZ","Phoenix","Southwest","The Grand Canyon is here."),
"Arkansas":("AR","Little Rock","Southeast","It has a park where you can dig for real diamonds."),
"California":("CA","Sacramento","West","More people live here than in any other state."),
"Colorado":("CO","Denver","West","Its capital is called the Mile High City."),
"Connecticut":("CT","Hartford","Northeast","Its nickname is the Nutmeg State."),
"Delaware":("DE","Dover","Northeast","It was the first state to join the United States."),
"Florida":("FL","Tallahassee","Southeast","It is a long peninsula with alligators in the Everglades."),
"Georgia":("GA","Atlanta","Southeast","It is famous for peaches."),
"Hawaii":("HI","Honolulu","West","It is made of volcanic islands in the Pacific Ocean."),
"Idaho":("ID","Boise","West","It grows lots of potatoes."),
"Illinois":("IL","Springfield","Midwest","The big city of Chicago sits on Lake Michigan here."),
"Indiana":("IN","Indianapolis","Midwest","It hosts a famous 500-mile car race."),
"Iowa":("IA","Des Moines","Midwest","It is surrounded by two big rivers: the Mississippi and the Missouri."),
"Kansas":("KS","Topeka","Midwest","It is near the middle of the lower 48 states, with fields of wheat."),
"Kentucky":("KY","Frankfort","Southeast","It is famous for horse racing and Mammoth Cave."),
"Louisiana":("LA","Baton Rouge","Southeast","The Mississippi River ends here at the Gulf of Mexico."),
"Maine":("ME","Augusta","Northeast","It is the farthest northeast state and famous for lobsters."),
"Maryland":("MD","Annapolis","Northeast","Chesapeake Bay almost cuts it in two."),
"Massachusetts":("MA","Boston","Northeast","The Pilgrims landed at Plymouth here."),
"Michigan":("MI","Lansing","Midwest","It is shaped like a mitten, plus a second piece up north."),
"Minnesota":("MN","Saint Paul","Midwest","It is called the Land of 10,000 Lakes."),
"Mississippi":("MS","Jackson","Southeast","It shares its name with a giant river on its western edge."),
"Missouri":("MO","Jefferson City","Midwest","The Gateway Arch is in St. Louis here."),
"Montana":("MT","Helena","West","It is called Big Sky Country."),
"Nebraska":("NE","Lincoln","Midwest","It is in the Great Plains, between South Dakota and Kansas."),
"Nevada":("NV","Carson City","West","Las Vegas is in this desert state."),
"New Hampshire":("NH","Concord","Northeast","Its motto is Live Free or Die."),
"New Jersey":("NJ","Trenton","Northeast","It is called the Garden State."),
"New Mexico":("NM","Santa Fe","Southwest","It has a huge hot-air balloon festival."),
"New York":("NY","Albany","Northeast","The Statue of Liberty stands here."),
"North Carolina":("NC","Raleigh","Southeast","The Wright brothers first flew a plane here."),
"North Dakota":("ND","Bismarck","Midwest","It touches Canada and sits right above South Dakota."),
"Ohio":("OH","Columbus","Midwest","Lots of astronauts, like Neil Armstrong, came from here."),
"Oklahoma":("OK","Oklahoma City","Southwest","It is shaped like a pan with a handle."),
"Oregon":("OR","Salem","West","Crater Lake, the deepest lake in the country, is here."),
"Pennsylvania":("PA","Harrisburg","Northeast","The Liberty Bell is in Philadelphia here."),
"Rhode Island":("RI","Providence","Northeast","It is the smallest state."),
"South Carolina":("SC","Columbia","Southeast","Its state tree is the palmetto palm."),
"South Dakota":("SD","Pierre","Midwest","Mount Rushmore is carved here."),
"Tennessee":("TN","Nashville","Southeast","Its capital is called Music City."),
"Texas":("TX","Austin","Southwest","It is the biggest state in the lower 48."),
"Utah":("UT","Salt Lake City","West","It has a giant salty lake."),
"Vermont":("VT","Montpelier","Northeast","It makes the most maple syrup in the country."),
"Virginia":("VA","Richmond","Southeast","Eight presidents were born here, including George Washington."),
"Washington":("WA","Olympia","West","It is in the far northwest corner of the lower 48."),
"West Virginia":("WV","Charleston","Southeast","It is called the Mountain State."),
"Wisconsin":("WI","Madison","Midwest","It is famous for cheese."),
"Wyoming":("WY","Cheyenne","West","Yellowstone, the first national park, is mostly here."),
}
LEVEL_A = ["California","Texas","Florida","New York","Alaska","Hawaii","Arizona","Washington","Colorado","Michigan"]
NORTHEAST_ZOOM = ["Delaware","Rhode Island","Connecticut","New Jersey","Maryland","Massachusetts","New Hampshire","Vermont"]
# Scavenger hunts: chained clues; each answer is a state name; each clue builds on the last.
HUNTS = [
dict(level="A", title="Coast to Coast", clues=[
 ("Start in the state where more people live than any other. It is on the Pacific coast.","California"),
 ("Go east to the biggest state in the lower 48. Yee-haw!","Texas"),
 ("Keep going east along the Gulf of Mexico to the peninsula state with alligators.","Florida"),
 ("Fly north up the Atlantic coast to the state with the Statue of Liberty.","New York"),
 ("Now take a long trip northwest to the biggest state of all.","Alaska"),
]),
dict(level="A", title="Islands, Canyons & Mittens", clues=[
 ("Begin on the volcanic islands in the Pacific Ocean.","Hawaii"),
 ("Fly to the mainland state with the Grand Canyon.","Arizona"),
 ("Go northeast to the state whose capital is the Mile High City.","Colorado"),
 ("Head far east to the state shaped like a mitten.","Michigan"),
 ("Finish in the far northwest corner of the lower 48.","Washington"),
]),
dict(level="B", title="Mississippi River Ride", clues=[
 ("Start in the Land of 10,000 Lakes, where the Mississippi River begins.","Minnesota"),
 ("Float south. The next state on the river's WEST bank is surrounded by two big rivers.","Iowa"),
 ("Keep floating south on the west bank to the state with the Gateway Arch.","Missouri"),
 ("Farther south on the west bank is the state where you can dig for diamonds.","Arkansas"),
 ("The river ends at the Gulf of Mexico in this state.","Louisiana"),
]),
dict(level="B", title="Founders' Trail", clues=[
 ("Start in the first state to join the United States.","Delaware"),
 ("Go north into the state with the Liberty Bell.","Pennsylvania"),
 ("Head northeast across New York to the state where the Pilgrims landed.","Massachusetts"),
 ("Visit Boston's tiny neighbor to the south, the smallest state.","Rhode Island"),
 ("Travel south to the state where George Washington was born.","Virginia"),
]),
dict(level="B", title="Wild West Loop", clues=[
 ("Start where Yellowstone, the first national park, is.","Wyoming"),
 ("Go north to Big Sky Country.","Montana"),
 ("Head west to the potato state next door.","Idaho"),
 ("Go south to the state with a giant salty lake.","Utah"),
 ("Go west to the desert state with Las Vegas.","Nevada"),
]),
]
